# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/yunkunliao/zhuzhu/xilinx-risc-v/vivado/generic/system.xdc

# IP: /home/yunkunliao/zhuzhu/xilinx-risc-v/ip/ila_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ila_0 || ORIG_REF_NAME==ila_0} -quiet] -quiet
